version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3005:80"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
